sudo: required
services:
  - docker
env:
  global:
    - IMAGE_NAME=adriaq/test
    - REGISTRY_USER=adriaq
    - REGISTRY_PASS=Tuf4Nn9u2aaQR8fBqnFx6tguYyjS2JMw
 
script:
  - docker build . --tag "$IMAGE_NAME" 
 
after_script:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
  - docker push "${IMAGE_NAME}:latest" 
